src/bmdef.h
Incorporate appropriate tuneups to BM_ASSERT, BM(_HAS)RESTRICT, and
BM(_HAS)FORCEINLINE when the NCBI C++ Toolkit's core headers have been
included.  (The C++ Toolkit historically applied these tuneups itself
via a wrapper for bm.h, but bmundef.h then dropped them, so auxiliary
headers such as bmalgo.h and bmserial.h always proceeded to use stock
settings.)
=> bmdef.h: Automatically integrate with the NCBI C++ Toolkit.

src/bmdef.h
I'll introduce this macro shortly per https://jira.ncbi.nlm.nih.gov/browse/CXX-9614.
=> bmdef.h: If NCBI_SSE is defined, define BMSSE*OPT accordingly.

src/bmdef.h
This compiler is only partially C++11 compliant, supporting move
constructors (and a number of other C++11-isms) but not noexcept.
=> bmdef.h: Make BMNOEXEPT empty under Microsoft Visual Studio 2013.

src/bmsse2.h
fixed warning:
warning C4244: 'initializing' : conversion from '__int64' to 'int', possible loss of data
=> bmsse2.h: Fix __int64 -> int conversion warning from Visual Studio

src/bmutil.h
This patch addresses an immediate problem on macOS.  I suspect you'll likewise want a conditional #include directive of <avx2intrin.h> for __m256i when BMAVX2OPT is defined.
=> bmutil.h: #include <emmintrin.h> as needed for __m128i.

src/bm.h
Reinstate the tmp_gap_blk initializer in set_range_no_check, and add
an identical one in clear_range_no_check, to address errors when
building with -Werror=maybe-uninitialized.
=> bvector<>::{set,clear}_range_no_check: Formally pre-zero tmp_gap_blk.

src/bm.h
Visual Studio 2015 requires this keyword when explicitly qualifying
the type, and Clang and GCC are fine either way.
=> bm.h: Use typename keyword for bm::bvector<Alloc>::optmode.

src/bmdef.h, src/bmserial.h
This formal change avoids compilation failures with `-Wextra -Werror`, as used by gpipe, and can be extended as necessary to accommodate non-GCC compilers.
=> encode_gap_block: Mark fallthroughs with a new BM_FALLTHROUGH macro.

src/bmdef.h, src/bmtrans.h
Address warnings observed with gcc -Wconversion.
(Yes, the type of an integer division's divisor formally affects the result type, I suppose for uniformity's sake.)
=> gap_transpose_engine::tmatrix_type: Explicitly static_cast matrix dimensions.

src/bmdef.h
Dispatch on the basis of C++14 __has_cpp_attribute for C++11 attribute
syntax, and GCC's __has_attribute extension for __attribute__.
The current logic turned out to result in warnings under ICC when using C++14 and below.
=> bmdef.h (BM_FALLTHROUGH): Rework to consult __has(_cpp)_attribute.

src/bmdef.h
Supply a conditional fallback definition as with __has_cpp_attribute,
since attempting to rely on "&&" short-circuiting resulted in warnings
from Microsoft Visual Studio (and possibly other compilers).
=> bmdef.h: Rework __has_attribute logic per Visual Studio warnings.

src/bmbmatrix.h
Return `bvector_type_const_ptr`, not `const bvector_type_ptr`, in which
the `const` had no effect due to applying at the wrong level.
Preemptively address a warning (with `-Wignored-qualifiers`) that's otherwise likely to break gbench builds using `-Werror`.
BTW, I suspect you meant "plane" throughout, but that may not be worth correcting at this point.
=> base_sparse_vector::plain: Correct const variant's return type.

src/bmdef.h
Don't try to use [[fallthrough]] under Clang 7 or older with C++14 or older;
in this situation, __has_cpp_attribute(fallthrough) succeeds but trying to
use the attribute fails with "error: use of the 'fallthrough' attribute is a
C++17 extension".
=> BM_FALLTHROUGH: Blacklist [[fallthrough]] in a Clang corner case.

CMakeLists.txt
Hello. This PR fixes the warnings reproduced on CMake 3.17.0-rc1:
```
CMake Warning (dev) at CMakeLists.txt:20 (if):
Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
Quoted variables like "MSVC" will no longer be dereferenced when the policy
is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at CMakeLists.txt:37 (elseif):
Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command …
```
=> fixed CMake warnings related to CMP0054 policy

src/bmfunc.h
Some compilers (at minimum GCC 7.3.0 with -Wconversion) otherwise
issue warnings about possibly lossy int -> unsigned short conversion
on the += lines, presumably due to implicit promotion of sums.
=> bitscan_wave: Defer unsigned short usage until return.

lang-maps/libbm/src/libbm.cpp
Fixes the threading problem for Rust bindings in https://github.com/tlk00/BitMagic/issues/61#issuecomment-723659872.
I'm checking for MSVC and falling back to GCC/Clang syntax, should I add more checks/systems?
=> make ex_buf__ into a thread local variable

src/bmdef.h
Require both Clang 7+ and C++17 or newer, rather than accepting either
on its own; otherwise, builds with strict flags (`-Wc++17-extensions`,
as implied by `-pedantic`) can trigger diagnostics.
=> BM_FALLTHROUGH: Correctly conditionalize [[fallthrough]] under Clang.

src/bm.h, src/bmbmatrix.h, src/bmfunc.h, src/bmsparsevec_parallel.h, src/bmxor.h
It's defined to supply a semicolon itself, and roughly 80% of calls
overall rely on that characteristic, so go with the flow to avoid
breaking under `-Werror=pedantic`.
=> bm*.h: Invoke BM_DECLARE_TEMP_BLOCK without a trailing semicolon.

lang-maps/libbm/src/libbm_impl.cpp
Fixes #65
I'm using the `BM_x86` flag defined in `bmdef.h` to limit `__cpuid` calls to `x86`, I think that is the proper solution?
With these changes I'm able to compile and test the [Rust bindings](https://github.com/luizirber/bitmagic-rs/pull/2) in aarch64/ppc64le/s390x platforms (tests are currently failing on s390x, but I don't have access to a machine to debug it :sweat_smile:)
=> Avoid x86 SIMD detection in other platforms

src/bmutil.h
At least under macOS, it was possible to get errors that
_mm_popcnt_u{32,64} were undeclared; another branch would have failed
due to direct inclusion of <avx2intrin.h>, which insists on being
included via <immintrin.h>.  <x86intrin.h> is overkill, but still not
all that heavy, and avoids any such complications.
=> bmutil.h: Simply go with <x86intrin.h> under (non-Windows) x86_64.

src/bmsse4.h
Actual inlining would likely be impractical, but formally inviting the
possibility avoids multiple-definition errors in some scenarios.
=> sse42_gap_test: Reinstate use of "inline" keyword.

src/bmserial.h
Ensure acc64 is always at least nominally used.
I used the same idiom as in f39ce89f.
=> deserializer<>::deserialize: Avoid warnings with assertions disabled.

src/bm.h, src/bmserial.h
It supplies one itself, and adding another can break builds with strict compilation settings (e.g., -Werror=pedantic), at least outside of a function.  Most invocations already lack extra semicolons.
=> Never follow BM_DECLARE_TEMP_BLOCK(...) with a semicolon.

src/bm.h
import_block uses the array's first element's bit position instead of the one specified by start, which can lead to the wrong bit being set in the bitblock in a case where a single bit is to be set for the block and the bit is not the first element of the array to be imported.
Minimal example to reproduce the issue:
```
bm::bvector<> bv;
bv.set(65540);
bv.optimize();
{
bm::bvector<>::bulk_insert_iterator it(bv);
*it = 0;
*it = 65540;
}
assert(bv.count() == 2);
assert(bv.get_bit(0));
assert(bv.get_bit(65540));
```
This example produces a bvector with the bits 0, 65536 and 65540 set, instead of the expected 0 and 65540.
=> Fix setting wrong bit in bitblock for import_block
